/*
  # Fix Invoice Type Column Reference

  1. Problem
    - The generate_invoice_after_payment() trigger function checks for invoice_type column
    - But invoices table doesn't have an invoice_type column
    - This causes manual payment approval to fail with "column invoice_type does not exist"

  2. Changes
    - Remove the invoice_type condition from the invoice existence check
    - The subscription_id is sufficient to identify if an invoice already exists
    
  3. Impact
    - Manual payment approval will work correctly
    - Invoice generation trigger will function properly
*/

-- Recreate the trigger function without invoice_type reference
CREATE OR REPLACE FUNCTION generate_invoice_after_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_subscription_id uuid;
BEGIN
  -- Only proceed if subscription was just activated via manual payment
  IF NEW.payment_status = 'paid' 
     AND OLD.payment_status = 'pending_payment'
     AND NEW.payment_method = 'manual' THEN
    
    -- Check if invoice already exists for this subscription
    IF NOT EXISTS (
      SELECT 1 FROM invoices 
      WHERE subscription_id = NEW.id
    ) THEN
      -- Invoice will be generated by the application layer
      -- This trigger just ensures the state is correct
      NULL;
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;